                                                    o
                                                    |
                                                    |
                                                    o
                                                    |
                                                    |
                                                    o
                                                    |
                                                    |
                                                    o
                                                    |
                                                    |
                                                    o
                                                  __| 
                                                 /   \
                                                o     o
                                                |     |
                                                |     |
                                                o     o
                                                |
                                                |
                                                o
                                                |
                                                |
                                                o
                                                |
                                                |
                                                o
                                            ____| 
                                           /     \
                                          o       o
                                          |
                                          |
                                          o
                                          |
                                          |
                                          o
                                          |
                                          |
                                          o
                                          |
                                          |
                                          o
                                          |
                                          |
                                          o
                                          |
                                          |
                                          o
                                          |
                                          |
                                          o
                                          |
                                          |
                                          o
                                          |
                                          |
                                          o
                                          |
                                          |
                                          o
                                          |
                                          |
                                          o
                                      ____|__ 
                                     /    |  \
                                    o     o   o
                                    |         |
                                    |         |
                                    o         o
                                    |
                                    |
                                    o
                                    |
                                    |
                                    o
                                    |
                                    |
                                    o
                                    |
                                    |
                                    o
                                    |
                                    |
                                    o
                                    |
                                    |
                                    o
                                    |
                                    |
                                    o
                                    |
                                    |
                                    o
                                    |
                                    |
                                    o
                                    |
                                    |
                                    o
                                    |
                                    |
                                    o
                                    |
                                    |
                                    o
                                    |
                                    |
                                    o
                                    |
                                    |
                                    o
                                  __| 
                                 /   \
                                o     o
                                |
                                |
                                o
                                |
                                |
                                o
                                |
                                |
                                o
                                |
                                |
                                o
                                |
                                |
                                o
                                |
                                |
                                o
                                |
                                |
                                o
                                |
                                |
                                o
                                |
                                |
                                o
                                |
                                |
                                o
                                |
                                |
                                o
                                |
                                |
                                o
                                |
                                |
                                o
                                |
                                |
                                o
                                |
                                |
                                o
                                |
                                |
                                o
                                |
                                |
                                o
                              __| 
                             /   \
                            o     o
                            |
                            |
                            o
                          __| 
                         /   \
                        o     o
                        |
                        |
                        o
                        |
                        |
                        o
                        |
                        |
                        o
                        |
                        |
                        o
                        |
                        |
                        o
                      __| 
                     /   \
                    o     o
                    |
                    |
                    o
                    |
                    |
                    o
                    |
                    |
                    o
                    |
                    |
                    o
                    |
                    |
                    o
                    |
                    |
                    o
                    |
                    |
                    o
                    |
                    |
                    o
                    |
                    |
                    o
                    |
                    |
                    o
                    |
                    |
                    o
                    |
                    |
                    o
                    |
                    |
                    o
                    |
                    |
                    o
                    |
                    |
                    o
                    |
                    |
                    o
                    |
                    |
                    o
                    |
                    |
                    o
                    |
                    |
                    o
                    |
                    |
                    o
                    |
                    |
                    o
                  __| 
                 /   \
                o     o
                |
                |
                o
                |
                |
                o
                |
                |
                o
                |
                |
                o
                |
                |
                o
                |
                |
                o
                |
                |
                o
                |
                |
                o
                |
                |
                o
                |
                |
                o
                |
                |
                o
                |
                |
                o
              __| 
             /   \
            o     o
            |
            |
            o
            |
            |
            o
            |
            |
            o
          __| 
         /   \
        o     o
        |     |
        |     |
        o     o
        |     |
        |     |
        o     o
        |     |
        |     |
        o     o
        |     |
        |     |
        o     o
        |
        |
        o
        |
        |
        o
        |
        |
        o
        |
        |
        o
        |
        |
        o
        |
        |
        o
        |
        |
        o
        |
        |
        o
        |
        |
        o
        |
        |
        o
        |
        |
        o
        |
        |
        o
        |
        |
        o
        |
        |
        o
        |
        |
        o
        |
        |
        o
        |
        |
        o
        |
        |
        o
        |
        |
        o
        |
        |
        o
        |
        |
        o
        |
        |
        o
        |
        |
        o
        |
        |
        o
        |
        |
        o
        |
        |
        o
        |
        |
        o
      __| 
     /   \
    o     o
    |
    |
    o
    |
    |
    o
    |
    |
    o
    |
    |
    o
    |
    |
    o
    |
    |
    o
    |
    |
    o
    |
    |
    o
    |
    |
    o
    |
    |
    o
    |
    |
    o
    |
    |
    o
    |
    |
    o
    |
    |
    o
    |
    |
    o
    |
    |
    o
    |
    |
    o
    |
    |
    o
    |
    |
    o
    |
    |
    o
    | 
   / \
  o   o
  |
  |
  o
  |
  |
  o
  |
  |
  o
  |
  |
  o
  |
  |
  o
  |
  |
  o
  |
  |
  o
  |
  |
  o
  |
  |
  o
  |
  |
  o
  |
  |
  x
